# Generated by Django 6.1.1 on 2026-10-06 22:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=300, verbose_name='نام کامل')),
                ('location', models.CharField(blank=True, max_length=1000, null=True, verbose_name='آدرس')),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='کد پستی')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='profile-customer-avatars/', verbose_name='عکس پروفایل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پروفایل مشتری',
                'verbose_name_plural': 'پروفایل مشتریان',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='sellerprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(max_length=10, unique=True, verbose_name='کد ملی')),
                ('shaba_number', models.CharField(blank=True, max_length=26, null=True, verbose_name='شماره شبا')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='profile-seller-avatars/', verbose_name='عکس پروفایل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پروفایل فروشنده',
                'verbose_name_plural': 'پروفایل فروشندگان',
                'ordering': ('-created_at',),
            },
        ),
    ]
