# Generated by Django 6.1.1 on 2026-09-30 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerprofile',
            options={'ordering': ('-created_at',), 'verbose_name': 'پروفایل مشتری', 'verbose_name_plural': 'پروفایل مشتریان'},
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='profile-avatars/', verbose_name='عکس پروفایل'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='full_name',
            field=models.CharField(max_length=300, verbose_name='نام کامل'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='location',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='کد پستی'),
        ),
        migrations.CreateModel(
            name='sellerprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(max_length=10, unique=True, verbose_name='کد ملی')),
                ('shaba_number', models.CharField(blank=True, max_length=26, null=True, verbose_name='شماره شبا')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پروفایل فروشنده',
                'verbose_name_plural': 'پروفایل فروشندگان',
                'ordering': ('-created_at',),
            },
        ),
    ]
