# Generated by Django 6.1.1 on 2026-10-07 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='wallet',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='کیف پول'),
        ),
    ]
