# Generated by Django 6.1.1 on 2026-10-04 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_customerprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='profile-seller-avatars/', verbose_name='عکس پروفایل'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='profile-customer-avatars/', verbose_name='عکس پروفایل'),
        ),
    ]
