# Generated by Django 6.1.1 on 2026-10-08 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='total',
            new_name='cart_total',
        ),
    ]
