# Generated by Django 6.1.1 on 2026-10-01 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام دسته بندی')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('name', models.CharField(max_length=100, verbose_name='نام محصول')),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('price', models.PositiveIntegerField()),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید')),
                ('status', models.CharField(choices=[('draft', 'پیش نویس'), ('published', 'منتشر شده'), ('archived', 'آرشیو شده')], default='draft', max_length=11, verbose_name='وضعیت')),
                ('category', models.ManyToManyField(related_name='products', to='products.category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
