# Generated by Django 6.1.1 on 2026-10-08 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='media/products-image/default.jpg', null=True, upload_to='products-image/', verbose_name='عکس پروفایل'),
        ),
    ]
